localization = {
    "en": {
        "very-low-income": "Very Low Income",
        "low-income": "Low Income",
        "moderate-income": "Moderate Income",
        "median-income": "Median Income",
        "high-income": "High Income",
        "up-to-20%-amhi": "up to 20% of AMHI",
        "21%-to-50%-amhi": "21% to 50% of AMHI",
        "51%-to-80%-amhi": "51% to 80% of AMHI",
        "81%-to-120%-amhi": "81% to 120% of AMHI",
        "121%+-amhi": "121% + of AMHI",
        "graph9-title": "Household Projections by Income Category",
        "graph-legend": "{prediction_year} households<br>and {year}-{prediction_year} change<br>",
        "graph10-title": "Household Projections by Household Size",
        "graphh-title": "Projected Households by Household Size and Income Category",
        "household-size": "Household Size",
        "income-category": "Income Category",
        "number-of-households": "Number of Households",
        "1-person": "1 Person",
        "2-person": "2 Person",
        "3-person": "3 Person",
        "4-person": "4 Person",
        "5+-person": "5+ Person",
        "hh-size": "HH Size",
        "graph11-title": "Projected Household Gain/Loss",
        "graph12-title": "Projected Municipal vs Regional Household Growth Rates by Income Category",
        "graph13-title": "Projected Community and Regional Household Growth Rates",
        "to": "to",
        "category": "Category",
        "growth-rate": "Growth Rate (%)",
        "error-scope": "Not Available in CD/Regional level. Please select CSD/Municipal level",
        "municipal": "Municipal",
        "regional": "Regional",
    },
    "fr": {
        "very-low-income": "Très faible revenu",
        "low-income": "Faible revenu",
        "moderate-income": "Revenue modéré",
        "median-income": "Revenu médian",
        "high-income": "Revenu élevé",
        "up-to-20%-amhi": "jusqu'à 20% de ce revenue",
        "21%-to-50%-amhi": "21% à 50% de ce revenue",
        "51%-to-80%-amhi": "51% à 80% de ce revenue",
        "81%-to-120%-amhi": "81% à 120% de ce revenue",
        "121%+-amhi": "121% + de ce revenue",
        "graph9-title": "Projections des ménages par catégorie de revenu",
        "graph-legend": "{prediction_year} foyers<br>et variation de {year}-{prediction_year}<br>",
        "graph10-title": "Projections des ménages par taille de ménage",
        "graphh-title": "Ménages projetés par taille du ménage et catégorie de revenu",
        "household-size": "La taille du ménage",
        "income-category": "Catégorie de revenu",
        "number-of-households": "Nombre de ménages",
        "1-person": "1 personne",
        "2-person": "2 personne",
        "3-person": "3 personne",
        "4-person": "4 personne",
        "5+-person": "5+ personne",
        "hh-size": "Taille du ménage",
        "graph11-title": "Gain/Perte projeté pour les ménages de",
        "graph12-title": "Taux de croissance des ménages municipaux et régionaux projetés par catégorie de revenu",
        "graph13-title": "Taux de croissance projetés des ménages communautaires et régionaux",
        "to": "à",
        "category": "Catégorie",
        "growth-rate": "Taux de croissance (%)",
        "error-scope": "Non disponible au niveau CD/régional. Veuillez sélectionner le niveau CSD/Municipal",
        "municipal": "Municipal",
        "regional": "Régional",
    }
}
