localization = {
    "en": {
        "very-low-income": "Very Low Income",
        "low-income": "Low Income",
        "moderate-income": "Moderate Income",
        "median-income": "Median Income",
        "high-income": "High Income",
        "price-format-label": "{b}<br> (${value})",
        "price-format-label-comp": " (${value}) ",
        "price-format-label-last": "{b}<br> (>${value})",
        "price-format-label-last-comp": " (>${value}) ",
        "up-to-20%-amhi": "up to 20% of AMHI",
        "21%-to-50%-amhi": "21% to 50% of AMHI",
        "51%-to-80%-amhi": "51% to 80% of AMHI",
        "81%-to-120%-amhi": "81% to 120% of AMHI",
        "121%+-amhi": "121% + of AMHI",
        "fig6-title-comparison": "Percentage of Households in Core Housing Need by Priority Population and Income "
                                 "Category, {default_year}",
        "income-category": "Income Category",
        "percent-hh": "% of HH",
        "affordable-shelter": "(Max. affordable shelter costs)",
        "fig-title": 'Percentage of Households in Core Housing Need, by Income Category,',
        "income": "Income",
        "vs": "vs",
    },
    "fr": {
        "very-low-income": "Très faible revenu",
        "low-income": "Faible revenu",
        "moderate-income": "Revenue modéré",
        "median-income": "Revenu médian",
        "high-income": "Revenu élevé",
        "price-format-label": "{b}<br> ({value}$)",
        "price-format-label-comp": " ({value}$) ",
        "price-format-label-last": "{b}<br> (>{value}$)",
        "price-format-label-last-comp": " (>{value}$) ",
        "up-to-20%-amhi": "jusqu'à 20% de ce revenue",
        "21%-to-50%-amhi": "21% à 50% de ce revenue",
        "51%-to-80%-amhi": "51% à 80% de ce revenue",
        "81%-to-120%-amhi": "81% à 120% de ce revenue",
        "121%+-amhi": "121% + de ce revenue",
        "fig6-title-comparison": "Pourcentage de ménages ayant des besoins impérieux de logement par population "
                                 "prioritaire et revenu Catégorie, {default_year}",
        "income-category": "Catégorie de revenu",
        "percent-hh": "% du ménage",
        "affordable-shelter": "(coût maximal du logement abordable)",
        "fig-title": 'Pourcentage de ménages ayant des besoins impérieux en matière de logement, <br>par catégorie de revenu',
        "income": "Revenu",
        "vs": "contre",
    }
}
