localization = {
    "en": {
        "very-low-income": "Very Low Income",
        "low-income": "Low Income",
        "moderate-income": "Moderate Income",
        "median-income": "Median Income",
        "high-income": "High Income",
        "price-format-label": "{b}<br> (${value})",
        "price-format-label-comp": " (${value}) ",
        "price-format-label-last": "{b}<br> (>${value})",
        "price-format-label-last-comp": " (>${value}) ",
        "up-to-20%-amhi": "up to 20% of AMHI",
        "21%-to-50%-amhi": "21% to 50% of AMHI",
        "51%-to-80%-amhi": "51% to 80% of AMHI",
        "81%-to-120%-amhi": "81% to 120% of AMHI",
        "121%+-amhi": "121% + of AMHI",
        "fig6-title": "Percentage of Households in Core Housing Need by Priority Population "
                                 "and Income Category,",
        "income-category": "Income Category",
        "percent-hh": "% of HH",
        "percent-pp-hh": "% of Priority Population HH",
        "affordable-shelter": "(Max. affordable shelter costs)",
        "fig-title": 'Percentage of Households in Core Housing Need, by Income Category,',
        "fig2-title": 'Percentage of Households in Core Housing Need, by Income Category and HH Size,',
        "fig5-title": 'Percentage of Households in Core Housing Need by Priority Population, ',
        "income": "Income",
        "vs": "vs",
        'single-mother-hh': 'Single mother-led HH',
        'women-led-hh': 'Women-led HH',
        'indigenous-hh': 'Indigenous HH',
        'minority-hh': 'Visible minority HH',
        'black-hh': 'Black-led HH',
        'migrant-hh': 'New migrant-led HH',
        'refugee-hh': 'Refugee claimant-led HH',
        '25-hh': 'HH head under 25',
        '65-hh': 'HH head over 65',
        '85-hh': 'HH head over 85',
        'physical-limit-hh': 'HH with physical activity limitation',
        'mental-hh': 'HH with cognitive, mental,<br>or addictions activity limitation',
        'transgender-hh': 'Transgender or Non-binary HH',
        'all-hh': 'Community (all HH)'
    },
    "fr": {
        "very-low-income": "Très faible revenu",
        "low-income": "Faible revenu",
        "moderate-income": "Revenue modéré",
        "median-income": "Revenu médian",
        "high-income": "Revenu élevé",
        "price-format-label": "{b}<br> ({value}$)",
        "price-format-label-comp": " ({value}$) ",
        "price-format-label-last": "{b}<br> (>{value}$)",
        "price-format-label-last-comp": " (>{value}$) ",
        "up-to-20%-amhi": "jusqu'à 20% de ce revenue",
        "21%-to-50%-amhi": "21% à 50% de ce revenue",
        "51%-to-80%-amhi": "51% à 80% de ce revenue",
        "81%-to-120%-amhi": "81% à 120% de ce revenue",
        "121%+-amhi": "121% + de ce revenue",
        "fig6-title": "Pourcentage de ménages ayant des besoins impérieux de logement par population "
                                 "prioritaire et revenu Catégorie, {default_year}",
        "income-category": "Catégorie de revenu",
        "percent-hh": "% du ménage",
        "percent-pp-hh": "% de ménages de la population prioritaire",
        "affordable-shelter": "(coût maximal du logement abordable)",
        "fig-title": 'Pourcentage de ménages ayant des besoins impérieux en matière de logement, <br>par catégorie de revenu',
        "fig2-title": 'Pourcentage de ménages ayant des besoins impérieux en matière de logement, <br>par catégorie de revenu et taille du ménage,',
        "fig5-title": 'Pourcentage de ménages ayant des besoins impérieux en matière de logement par population prioritaire, ',
        "income": "Revenu",
        "vs": "contre",
        'single-mother-hh': 'Ménages ayant à leur tête une mère seule',
        'women-led-hh': 'Ménages ayant à leur tête une femme',
        'indigenous-hh': 'Ménages autochtones',
        'minority-hh': 'Ménages de minorité visible',
        'black-hh': 'Ménages ayant à leur tête une personne noire',
        'migrant-hh': 'Ménages ayant à leur tête un nouvel immigrant',
        'refugee-hh': 'Ménages ayant à leur tête un demandeur de statut de réfugié',
        '25-hh': 'Chefs de ménage de moins de 25 ans',
        '65-hh': 'Chefs de ménage de plus de 65 ans',
        '85-hh': 'Chefs de ménage de plus de 85 ans',
        'physical-limit-hh': 'Ménages ayant des limitations physiques',
        'mental-hh': 'Ménages ayant des limitations mentales',
        'transgender-hh': 'Ménages ayant des membres transgenres ou non binaire',
        'all-hh': 'Communauté (tous les ménages)'
    }
}
