localization = {
    "en": {
        "very-low-income": "Very Low Income",
        "low-income": "Low Income",
        "moderate-income": "Moderate Income",
        "median-income": "Median Income",
        "high-income": "High Income",
        "up-to-20%-amhi": "up to 20% of AMHI",
        "21%-to-50%-amhi": "21% to 50% of AMHI",
        "51%-to-80%-amhi": "51% to 80% of AMHI",
        "81%-to-120%-amhi": "81% to 120% of AMHI",
        "121%+-amhi": "121% + of AMHI",
        "price-format-label": "{b}<br> (${value})",
        "price-format-label-comp": " (${value}) ",
        "price-format-label-last": "{b}<br> (>${value})",
        "price-format-label-last-comp": " (>${value}) ",
        "household-size": "Household Size",
        "income-category": "Income Category",
        "income": "Income",
        "fig-title": "Percentage of Indigenous Households in Core Housing Need, by Income and HH Size",
        "fig2-title": "Percentage of Indigenous Households in Core Housing Need, by Income Category",
        "number-of-households": "Number of Households",
        "1-person": "1 Person",
        "2-person": "2 Person",
        "3-person": "3 Person",
        "4-person": "4 Person",
        "5+-person": "5+ Person",
        "hh-size": "HH Size",
        "affordable-shelter": "(Max. affordable shelter costs)",
        "percent-ind-hh": "% of Indigenous HH",
    },
    "fr": {
        "very-low-income": "Très faible revenu",
        "low-income": "Faible revenu",
        "moderate-income": "Revenue modéré",
        "median-income": "Revenu médian",
        "high-income": "Revenu élevé",
        "up-to-20%-amhi": "jusqu'à 20% de ce revenue",
        "21%-to-50%-amhi": "21% à 50% de ce revenue",
        "51%-to-80%-amhi": "51% à 80% de ce revenue",
        "81%-to-120%-amhi": "81% à 120% de ce revenue",
        "121%+-amhi": "121% + de ce revenue",
        "price-format-label": "{b}<br> ({value}$)",
        "price-format-label-comp": " ({value}$) ",
        "price-format-label-last": "{b}<br> (>{value}$)",
        "price-format-label-last-comp": " (>{value}$) ",
        "household-size": "La taille du ménage",
        "income-category": "Catégorie de revenu",
        "income": "Revenu",
        "fig-title": "Pourcentage de ménages autochtones ayant des besoins impérieux en matière de logement, selon le revenu et la taille du ménage",
        "fig2-title": "Pourcentage de ménages autochtones ayant des besoins impérieux en matière de logement, par catégorie de revenu",
        "number-of-households": "Nombre de ménages",
        "1-person": "1 personne",
        "2-person": "2 personne",
        "3-person": "3 personne",
        "4-person": "4 personne",
        "5+-person": "5+ personne",
        "hh-size": "Taille du ménage",
        "affordable-shelter": "(coût maximal du logement abordable)",
        "percent-ind-hh": "% de ménages autochtones",
    }
}
